-- Vault X TCG schema updates
-- Run this once in Supabase SQL Editor before deploying the latest app.

alter table public.cards
add column if not exists game text default 'Pokemon';

update public.cards
set game = language,
    language = 'English'
where language in ('Pokemon', 'One Piece', 'Yu-Gi-Oh', 'Magic', 'Sports');

update public.cards
set game = 'Pokemon'
where game is null or game = '';

create table if not exists public.inventory_transactions (
  id bigint generated by default as identity primary key,
  company_id bigint not null,
  inventory_id text,
  card_number text,
  transaction_type text not null,
  quantity numeric default 0,
  cost numeric default 0,
  price numeric default 0,
  notes text,
  user_email text,
  created_at timestamptz not null default now()
);

create index if not exists inventory_transactions_company_created_idx
on public.inventory_transactions (company_id, created_at desc);

create index if not exists inventory_transactions_inventory_idx
on public.inventory_transactions (company_id, inventory_id);

create index if not exists activity_log_company_created_idx
on public.activity_log (company_id, created_at desc);

create index if not exists cards_company_status_idx
on public.cards (company_id, status);

create index if not exists cards_company_category_idx
on public.cards (company_id, category);

create index if not exists cards_company_game_idx
on public.cards (company_id, game);
